version: '2.3'

services:
  ruqqus:
    build:
      context: .
    volumes:
      - "./:/opt/ruqqus/service"
    environment:
      - domain=localhost
      - REDIS_URL=redis://redis
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - DATABASE_CONNECTION_POOL_URL=postgres://postgres@postgres:5432/postgres
      - PYTHONPATH="/opt/ruqqus/service"
      - MASTER_KEY=${MASTER_KEY:-KTVciAUQFpFh2WdJ/oiHJlxl6FvzRZp8kYzAAv3l2OA=}
      - SESSION_COOKIE_SECURE=false
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FORCE_HTTPS=0

      - HCAPTCHA_SECRET=5436ertfgcvbnfgcy
      - CLOUDFLARE_KEY=5436ertfgcvbnfgcy
      - AWS_ACCESS_KEY_ID=5436ertfgcvbnfgcy
      - AWS_SECRET_ACCESS_KEY=5436ertfgcvbnfgcy
      - DISCORD_BOT_TOKEN=5436ertfgcvbnfgcy
      - GIPHY_KEY=5436ertfgcvbnfgcy
      - MAINGUN_KEY=5436ertfgcvbnfgcy
      - CLOUDFLARE_ZONE=5436ertfgcvbnfgcy
    links:
      - "redis"
      - "postgres"
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    volumes:
      - ./redis.conf:/opt/ruqqus/redis.conf
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12.3
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
      - "./seed-db.sql:/docker-entrypoint-initdb.d/10-seed-db.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
