version: '2.3'

services:
  vue-frontend:
    build:
      context: ../ruqqus-vue
    volumes:
      - "../ruqqus-vue:/var/lib/www"
    links:
      - "ruqqus"
    ports:
      - "8080:8080"
  ruqqus:
    build:
      context: .
    volumes:
      - "./:/opt/ruqqus/service"
    environment:
      - domain=ruqqus.localhost:8000
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - DATABASE_CONNECTION_POOL_URL=postgres://postgres@postgres:5432/postgres
      - PYTHONPATH="/opt/ruqqus/service"
      - MASTER_KEY=${MASTER_KEY:-KTVciAUQFpFh2WdJ/oiHJlxl6FvzRZp8kYzAAv3l2OA=}
      - SESSION_COOKIE_SECURE=false
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    links:
      - "redis"
      - "postgres"
    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
